site_name: Cardlink API SDK
site_description: Python библиотека для работы с Cardlink API
site_author: LaFTon Technology
repo_url: https://github.com/LaFTonTechnology/cardlink
repo_name: cardlink

nav:
  - Home: index.md
  - Methods: methods.md
  - Types: types.md
  - Examples: examples.md

theme:
  language: ru
  name: material
  logo: assets/cardlink-logo.png
  favicon: images/cardlink-logo.ico
  palette:
    primary: indigo
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: auto
